### ISSUE TITLE
 InvalidPolicyDocumentI

### ISSUE THREAD

**Issue by KurtKim** [Beomi/s3-direct-uploader-demo#1]
안녕하세요 

https://beomi.github.io/2017/12/15/Direct-upload-to-S3-with-Lambda/

위 글에 나와있는데로 진행을 하고 있는데, 

업로드를 진행을 하면 

InvalidPolicyDocument, Invalid Policy: Invalid JSON.

이런 메세지를 리턴 합니다. ㅠㅠ

혹시 글을 작성 하셨을때와 지금이랑 바꿔야 할 부분이 있을까요??

**Comment by Beomi** [comment]
안녕하세요,
글쓴 시점 만든 프로젝트는 아직 잘 동작하고 있는데요, 혹시 바뀐 부분이 있는지 확인하고 코멘트 다시 드리겠습니다 :)

**Comment by KurtKim** [comment]
빠른 답변 감사드립니다.


        request_payload = json.loads(event['body'])

        if request_payload.get('headers'):
            response_data = sign_headers(request_payload['headers'])
        else:
            credential = list([c for c in request_payload['conditions'] if 'x-amz-credential' in c][0].values())[0]
            print(credential, type(credential))
            credential = str(credential)
            response_data = sign_policy(json.dumps(event).encode('utf-8'), credential)
        return {
            "statusCode": 200,
            "body": json.dumps(response_data)
        }

람다에서 statusCode가 없다는  에러가 나서 이런식으로 바꿨는데 혹시 이게 문제가 될까요?

**Comment by KurtKim** [comment]
Aㅏ.. severless 프레임워크에 무리하게 집어넣으려고하니까 에러가 났던 것 같습니다.

람다랑 게이트웨이api를 따로 만들어주니까 잘 도네요 ㅜㅜ

감사합니다.
